=== VictorOteroUFV/Practica1_DIS/Practica1_DIS/pedidos.dtd
<!DOCTYPE pedidos
[
<!ELEMENT pedidos (cantidad, cliente, destinatario, direccion_entrega, fecha_entrega, productos)*>
<!ELEMENT cantidad (#PCDATA)*>
<!ELEMENT cliente (apellido, direccion, email, nombre, numero_telefono)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT direccion (calle, codigo_postal, numero, pais, poblacion)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numero_telefono (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT direccion_entrega (calle, codigo_postal, numero, pais, poblacion)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT fecha_entrega (#PCDATA)>
<!ELEMENT productos (codigo, descripcion, localizacion, nombre, pendiente, stock)*>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT localizacion (estante, estanteria, pasillo)>
<!ELEMENT estante (#PCDATA)>
<!ELEMENT estanteria (#PCDATA)>
<!ELEMENT pasillo (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pendiente (#PCDATA)>
<!ELEMENT stock (#PCDATA)>
]
>

=== VictorOteroUFV/Practica1_DIS/Practica1_DIS/pedidos.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE pedidos SYSTEM "pedidos.dtd" >
<pedidos>
    <cantidad>1</cantidad>
    <cliente>
        <apellido>a</apellido>
        <direccion>
            <calle>a</calle>
            <codigo_postal>1</codigo_postal>
            <numero>1</numero>
            <pais>a</pais>
            <poblacion>1</poblacion>
        </direccion>
        <email>a</email>
        <nombre>a</nombre>
        <numero_telefono>1</numero_telefono>
    </cliente>
    <destinatario>a</destinatario>
    <direccion_entrega>
        <calle>a</calle>
        <codigo_postal>1</codigo_postal>
        <numero>1</numero>
        <pais>a</pais>
        <poblacion>1</poblacion>
    </direccion_entrega>
    <fecha_entrega>2020-03-13T17:13:55.386+01:00</fecha_entrega>
    <productos>
        <codigo>1</codigo>
        <descripcion>a</descripcion>
        <localizacion>
            <estante>1</estante>
            <estanteria>2</estanteria>
            <pasillo>1</pasillo>
        </localizacion>
        <nombre>a</nombre>
        <pendiente>1</pendiente>
        <stock>1</stock>
    </productos>
</pedidos>

=== VictorOteroUFV/Practica1_DIS/Practica1_DIS/EjemploconDTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE EjemploconDTD SYSTEM "pedidos.dtd" >
<pedidos>
    <cantidad>1</cantidad>
    <cantidad>1</cantidad>
    <cliente>
        <apellido>1</apellido>
        <direccion>
            <calle>1</calle>
            <codigo_postal>1</codigo_postal>
            <numero>1</numero>
            <pais>1</pais>
            <poblacion>1</poblacion>
        </direccion>
        <email>1</email>
        <nombre>1</nombre>
        <numero_telefono>1</numero_telefono>
    </cliente>
    <destinatario>1</destinatario>
    <direccion_entrega>
        <calle>1</calle>
        <codigo_postal>1</codigo_postal>
        <numero>1</numero>
        <pais>1</pais>
        <poblacion>1</poblacion>
    </direccion_entrega>
    <fecha_entrega>2020-03-13T17:01:14.248+01:00</fecha_entrega>
    <productos>
        <codigo>1</codigo>
        <descripcion>1</descripcion>
        <localizacion>
            <estante>1</estante>
            <estanteria>1</estanteria>
            <pasillo>1</pasillo>
        </localizacion>
        <nombre>1</nombre>
        <pendiente>1</pendiente>
        <stock>1</stock>
    </productos>
    <productos>
        <codigo>1</codigo>
        <descripcion>1</descripcion>
        <localizacion>
            <estante>1</estante>
            <estanteria>1</estanteria>
            <pasillo>1</pasillo>
        </localizacion>
        <nombre>1</nombre>
        <pendiente>1</pendiente>
        <stock>1</stock>
    </productos>
</pedidos>
